### PR TITLE
Add configuration to exit after retrieving JWTs (closes #121)

### LINKED ISSUE #121: Add ability to exit on successful retrieval of JWT SVID

### PR DESCRIPTION
**Pull request by keeganwitt**

### CODE REVIEW

**Comment by kfox1111** [comment]
Why two flags? There ever going to be a case where both jwt and x509 are enabled at the same time? If so, it probably should wait for both? If two flags, it may be confusing in that case.

**Comment by faisal-memon** [comment]
Im planning to do a small refactor to create a daemon mode flag. when disabled will just download the x509 and/or JWTs and then exit. That should cover this with only a single flag.

**Comment by keeganwitt** [comment]
> Why two flags? There ever going to be a case where both jwt and x509 are enabled at the same time? If so, it probably should wait for both? If two flags, it may be confusing in that case.

Yes, I was thinking some use cases might require both. Ideally, yes, it would wait for both. But I wasn't sure how to implement that, particularly since there might be multiple JWTs. If someone can guide me with an idea, I'll give it a shot.

**Comment by faisal-memon** [comment]
@keeganwitt Finally got around to creating the PR i mentioned above with a single `daemon_mode` flag. Please take a look and lmk if its ok to close this PR. https://github.com/spiffe/spiffe-helper/pull/161

**Comment by keeganwitt** [comment]
Conceptually, yea, think that will solve what I was trying to do here.

**Pull request closed without merging**
